apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
data:
  config.properties: |
    name={{ .Values.name }}
    namespace={{ .Values.namespace }}
    git.ref={{ .Values.git.ref }}
    git.commit={{ .Values.git.commit }}
    app.image={{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
    app.logging={{ .Values.app.logging }}
    app.tracing={{ .Values.app.tracing }}